name: Kola Farms
favicon: null
layout_spectrum: 0.4535466942470521
typography_spectrum: 0.6110892824362963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.464103756705299
  lightness: 0.5978570145089179
  saturation: 0.7267702254466712
  rhythmicContrast: 0.267965403618291
purpose: []
