name: Kola Farms
favicon: null
layout_spectrum: 0.76308
typography_spectrum: 0.6110892824362963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe6d2'
    - '#0a002a'
    - '#3e4781'
    - '#362c4a'
    - '#898583'
  brandStrength: 0.5
  lightness: 0.5978570145089179
  saturation: 0.7267702254466712
  rhythmicContrast: 0.267965403618291
purpose: []
