name: Kola Farms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11291
title: 'Locally Grown California Cannabis '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe6d2'
    - '#0a002a'
    - '#3e4781'
    - '#362c4a'
    - '#898583'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
