title: 'Locally Grown California Cannabis '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.283208
  brandStrength: 0
  lightness: 0.4580201
  brandColors:
    - '#eaeaea'
    - '#b09e92'
    - '#170051'
    - '#312c68'
    - '#4b5b82'
  rhythmicContrast: 0.4849624
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kola Farms
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.05263158
layout_spectrum: 0.641604
