name: Kola Farms
favicon: null
layout_spectrum: 0.69505
typography_spectrum: 0.6063373
title: 'Kola Farms - Locally Grown '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020302'
    - '#5C545C'
    - '#FF9A30'
    - '#FFFF88'
    - '#B43901'
  brandStrength: 0.25
  lightness: 0.5338346
  saturation: 0.4974937
  rhythmicContrast: 0.3076441
purpose: []
